### ISSUE TITLE
Devices or Services for Smart Watering System

### ISSUE THREAD

**Issue by dueltschi** [py-smart-gardena/hass-gardena-smart-system#10]
Hi,

First, thanks a lot for all your great work! It's soo great to be finally able to integrate HA with Gardena Smart system. 

I've successfully activated the integration and it shows up in HA integrations. I have the smart watering system only (no mower, nor irrigation system). But the integration doesn't show any device nor entity. Also I was not able to find any service nor state related to the smart watering system. 

Can you please help me on how to use this integration? I would like to see the current status and activate/disable watering using a switch. 

Thanks,
D

**Comment by northpower25** [comment]
After you have installed the integration you found depending on your Gardena Setup different Devices and Entitys. 
![5C83CE81-644A-419B-97FF-81A5E4BC819A](https://user-images.githubusercontent.com/36472486/83406406-dba8ed80-a40e-11ea-8a92-30d19f51ea8f.jpeg)

Every device stand for one physical Gardena Device (Mover, Sensor, smart Watering)

![7A0732BE-E04D-4C18-9E34-60E0A1526C80](https://user-images.githubusercontent.com/36472486/83406456-f713f880-a40e-11ea-8970-b7ed08ea7bbd.jpeg)

Every Entity stand for a sensor (Binary, battery etc.) from the devices above
![A4F23A42-51D3-4012-B474-EF067183ADE9](https://user-images.githubusercontent.com/36472486/83406529-1f035c00-a40f-11ea-966a-45100df4bcad.jpeg)

The entitys you can use to display in the frontend like those examples
![894DD901-64F4-428E-9C89-536F194EBD73](https://user-images.githubusercontent.com/36472486/83406801-b8327280-a40f-11ea-8f4d-e815207a9a82.jpeg)
![EE044176-3DE8-450D-8F14-6E06496D2888](https://user-images.githubusercontent.com/36472486/83406803-b8cb0900-a40f-11ea-9878-d8f29b5b3237.jpeg)
![1E6D8C51-178A-46F1-8461-7258D4D3B0D9](https://user-images.githubusercontent.com/36472486/83406805-b9639f80-a40f-11ea-974f-3b6e9782ce77.jpeg)

And for example switches or the mower you can control direct from the frontend.

But on the other hands you can use the entitys for automations and scripts like those...

![791F6377-B6A1-48A5-8782-5967C55D3668](https://user-images.githubusercontent.com/36472486/83407046-38f16e80-a410-11ea-831c-4deb414063a6.jpeg)

**Comment by dueltschi** [comment]
Thanks a lot. In my HA, no device are shown...

<img width="267" alt="image" src="https://user-images.githubusercontent.com/59840460/83407701-9508c280-a411-11ea-8686-b1e7b737160f.png">

How can I fix that?

**Comment by dueltschi** [comment]
just found the following error in my HA logs: 

Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:92 
First occurred: 14:44:37 (1 occurrences) 
Last logged: 14:44:37

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/config/custom_components/gardena_smart_system/__init__.py", line 51, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 92, in start
    raise Exception("No locations found")
Exception: No locations found

**Comment by dueltschi** [comment]
any suggestions?

**Comment by dueltschi** [comment]
even more errors found in the logs: 

Logger: gardena.smart_system
Source: custom_components/gardena_smart_system/__init__.py:88 
First occurred: 14:44:37 (1 occurrences) 
Last logged: 14:44:37

403 : {'message': 'Forbidden'}


Logger: gardena.smart_system
Source: custom_components/gardena_smart_system/config_flow.py:133 
First occurred: 14:44:36 (1 occurrences) 
Last logged: 14:44:36

403 : {'message': 'Forbidden'}

**Comment by northpower25** [comment]
It looks like your connection between your Gardena Account (do yo have an Gateway?) and the Gardena API is broken 🤔 See you your devices or can control those on the Gardena app if you are not connected to your home network?

**Comment by dueltschi** [comment]
just tested. disabled wifi & used 4g connection only from my phone. Opened Gardena app and started watering. It works. The watering started

**Comment by northpower25** [comment]
Have you anything (like firewall or others) they block the traffic between the gardena gatway and Gardena Api service on the web and on the one side and on the other between gardena Api and your Home Assistant instance?

**Comment by dueltschi** [comment]
yes i do have a Gardena gateway. which is connected via Lan cable to my internet router. No additional firewall or other. And usage via Gardena app using 4g connection works too.

**Comment by northpower25** [comment]
> just tested. disabled wifi & used 4g connection only from my phone. Opened Gardena app and started watering. It works. The watering started

Okay the Connection between your Gardena Gateway and the Gardena API on the web shut work 👍🏻 No you have to clear the web connection between Gardena API and HomeAssistant.

**Comment by dueltschi** [comment]
"clear the web connection between Gardena API and HomeAssistant". how to do that? 
Many thanks for your support!

**Comment by northpower25** [comment]
@grm @osks do you have any idea based on the logs from @dueltschi?

**Comment by osks** [comment]
I've seen the 403 error myself, but I don't have any ideas to why it happens. Best idea so far is to try to improve the stability. If you get this error, you might have to restart to get it working again, and that's not good enough.

> Logger: gardena.smart_system
> Source: custom_components/gardena_smart_system/**init**.py:88
> First occurred: 14:44:37 (1 occurrences)
> Last logged: 14:44:37
> 
> 403 : {'message': 'Forbidden'}

See also #12.

**Comment by northpower25** [comment]
@osks @dueltschi Please Check this -> https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/5#issuecomment-636923978

**Comment by grm** [comment]
Yes let 24h pass to check if the solution solves by itself.
I am not sure about the 24h delay, i can't remember having this issue when creating the app...

**Comment by dueltschi** [comment]
still same issue occurs. have restarted. still 403 : {'message': 'Forbidden'} and No locations found. Any suggestions?

**Comment by grm** [comment]
Strange, i do not understand the reason.
Would you agree to send me your creds and API key by mail (from my pofile) so i can debug more deeply ?
(you can change them before and will be able to change them afterwards) 

Grm

**Comment by dueltschi** [comment]
sure. I just sent you an email with the details. Thank you @grm!

**Comment by grm** [comment]
Thanks @dueltschi , i just tried my working code with your creds and i did not succeed. Everything looks fine on my sde (your API are connected, ...)

As Gardena is having issues with their API, we should let them correct issues as it might be related.

**Comment by northpower25** [comment]
@dueltschi please check this solution for the issue and give us a feedback if it works -> https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/5#issuecomment-638851191

**Comment by dueltschi** [comment]
it works perfectly. Now I can see 1 device + 2 entities in HA. Perfect! Thanks a lot guys!

**Comment by grm** [comment]
Great, I close this issue and keep the first one here : https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/5
