### ISSUE TITLE
Actions taken in Gardena App not reported to HA

### ISSUE THREAD

**Issue by mmick08** [py-smart-gardena/hass-gardena-smart-system#102]
Hi Guys,

I am facing the issue that Actions taken within the Gardena app f.e. "_start Irrigation_" are not reported to HA and so the Switch state is not up to date. Reverse everything is working.

Best Regards

**Comment by janssenk23** [comment]
hi all,

I'm having issues with integrating our Gardena Sileno Smart robotic mower with home assistant as well.
Until before winter, everything was running fine.
After winter recess, I'm having troubles getting correct values in Home Assistant
Tried generating a new api key on the husqvarna developer portal, but to no avail.
So contacted support, and received following answer:

Quote
Thanks for your messages regarding your smart Robotic Lawnmower integration with Home Assistant. It’s a pleasure to see that you’re building up your individual smart home experience by using our Developer Portal.

As we do not know this solution in detail, I might outline that we have slightly updated our API during winter season to improve stability and robustness for the upcoming gardening season. Please have a look at https://developer.husqvarnagroup.cloud/apis/GARDENA+smart+system+API#release-notes to check the slight changes which might affect your integration. Furthermore you might have to check that your websocket connection remains open and connected to keep all needed status events as expected.
/Quote

So...
I sure hope that one of the developer contributors can have a quick look at the changes in API, and the comment about the websocket connection to get updates back from gardena to home assistant, and can build us a new version of the gardena/husqvarna plugin ???

Kind regards.

**Comment by rsonnenschein** [comment]
Hi guys,

I had the same issue, but updating to the latest beta version solved it for me.

Best regards

**Comment by tobiasbayer** [comment]
Unfortunately, upgrading to the latest beta did not fix the issue for me. I'm still getting

``` ERROR (Thread-3) [websocket] error from callback <bound method Client.on_open of <gardena.smart_system.Client object at 0x6baceac0>>: on_open() missing 1 required positional argument: 'ws'```

**Comment by janssenk23** [comment]
I wonder if "outbound tcp" traffic that needs websockets is a "home assistant" issue, or a "plugin" issue.
(besides possible API changes that might break the integration)

Hope one of the developers can have a look at it soon.

**Comment by grm** [comment]
Hello, 
Try to update too the beta version of the integration if you are using the stable one (or vice versa).
Your issue seems to be related to a breaking change in one of the underlying library.

Please tell me if it works or not !

**Comment by janssenk23** [comment]
Solution confirmed !
Solved with hass-gardena-smart-system-0.2.5b4 !
Was running version 0.2.3
Didn't see a way in home assistant to update to a beta version, so followed the manual procedure.
- download the beta files from github
- backup home assistant custom_components\gardena_smart_system
- overwrite with new/beta 0.2.5b4
- restart home assistant

Updates from gardena are received & processed by home assistant !

Thank you very much !

**Comment by mmick08** [comment]
Hi @janssenk23 ,

can confirm its working now :) thank you!

Regards Manuel
