### ISSUE TITLE
Can't find any devices

### ISSUE THREAD

**Issue by Johnyyy85** [py-smart-gardena/hass-gardena-smart-system#11]
Hi,

There are 0 entiteties and devices. Am i doing something wrong?

thanks

![image](https://user-images.githubusercontent.com/65047570/83407559-4529fb80-a411-11ea-9c04-2018baf9d75f.png)

**Comment by dueltschi** [comment]
same here 

<img width="267" alt="image" src="https://user-images.githubusercontent.com/59840460/83407643-70ace600-a411-11ea-961b-f2099f4d6231.png">

**Comment by osks** [comment]
How did you install? Which "version" (commit) are you running?

**Comment by TheFitzZZ** [comment]
Got mine configured now as well - seeing the same issue. 

Running HA Supervised, Integration on commit #ebb01e5

**Comment by northpower25** [comment]
@TheFitzZZ  could you please attach logs @osks It looks like the same problem like #12 and #10

**Comment by TheFitzZZ** [comment]
Sorry for not thinking of that:

Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:92
First occurred: 15:49:03 (1 occurrences)
Last logged: 15:49:03

```
Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/config/custom_components/gardena_smart_system/__init__.py", line 51, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 92, in start
    raise Exception("No locations found")
Exception: No locations found
```

```
Logger: gardena.smart_system
Source: custom_components/gardena_smart_system/__init__.py:88
First occurred: 16:05:14 (1 occurrences)
Last logged: 16:05:14

403 : {'message': 'Forbidden'}
```

![image](https://user-images.githubusercontent.com/13013440/83418670-47e21c00-a424-11ea-8be9-24b3988f8bd5.png)

**Comment by northpower25** [comment]
@dueltschi @TheFitzZZ Please Check this -> https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/5#issuecomment-636923978

**Comment by TheFitzZZ** [comment]
Will wait a day or two and report back :-)

**Comment by dueltschi** [comment]
same here. Will report back in a few days. Thanks Guys!

**Comment by grm** [comment]
Maybe on of you would you agree to send me your creds and API key by mail (from my profile) so i can debug more deeply ?
(you can change them before and will be able to change them afterwards)

Grm

**Comment by grm** [comment]
Gardena is currently having issues with its API.
We need to let them sole their issue as it si probably related !

**Comment by ApplesandPears** [comment]
Guys, for everyone who wants to integrate Gardena Smart System into Home Assistant. There is an alternative way of doing this.

Go to "Configuration / Einstellungen" then to "Integrations / Integrationen", click the "+" in the bottom right corner, Search for "HomeKit Controller", Click on it and then choose from the drop down menu the Gardena Smart System. Enter the HomeKit code, printed on the back of the Gardena Smart Gateway - et voilà the Gardena Bridge including all Switches and Sensors is now available in Home Assistant.

From there, if you're an iOS User, you can expose those devices to the HA HomeBridge. 

![image](https://user-images.githubusercontent.com/56008284/83750661-e5785e00-a665-11ea-9abd-15387f43de0f.png)

**Comment by ApplesandPears** [comment]
@grm What's the advantage of using the Py integration over the HomeKit  Controller method?

**Comment by grm** [comment]
I never used homekit, I will try to find out how this works, but I can already tell : 
- advantage : to be independant from an apple product (i do not know if we have to create an account on apple and do we need to use their servers and by doing so, we augment the point of failures)
- this product may be vendor locked, and apple decide what can be done through their API and decide to stop an integration because they have their own (like on ios store)
- other advantage : independance from another third party tools and decision to start gaining money on something like that 

I may have to dig deeper on homekit in order to have a better insight, but these are my first impressions. And on your sides, do you see any advantage/inconvenient of each solutions ?

**Comment by northpower25** [comment]
@TheFitzZZ @Johnyyy85 please check this solution for the issue and give us a feedback if it works -> https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/5#issuecomment-638851191

**Comment by TheFitzZZ** [comment]
Awesome, works, thanks!

**Comment by ApplesandPears** [comment]
@grm there are two sides of HoneKit. 

The HomeKit-Controller can connect devices that have native HomeKit Integration. That’s how you import devices into Home Assistant. You don’t need a Apple device for that. 

The HomeKit Bridge will expose all devices, entities, automations etc to Apple HoneKit. To access HomeKit itself then, you need e.g.  an iPhone

So my assumption would be including Gardena Bridge through HomeKit-Controller (!) should work for everyone. 

The HomeKit Bridge is just something for Apple Users...

Do you want to take a look on it? I could document it ...

**Comment by TheFitzZZ** [comment]
I have both installed. The HomeKit part actually exposes a little less information, as the garden sensor is lacking soil temp and battery information. Smart irrigation seems to be identical, since it's only exposing the valve control. Don't have the smart version of the mower so don't know about that :-)

Also changing the duration of the irrigation isn't possible, which is quite useful for automation. My current HomeKit based automation needs to close and re-open to get more than the standard 20 mins :-).

**Comment by ApplesandPears** [comment]
@TheFitzZZ Thanks for your feedback. I don’t have the irrigation, just the water control and sensors. I can automate it quite well and the water control can be activated for as long as you want or as short as you want. Is this different with the irrigation control?

@grm here is a article which will give you better understanding 
https://www.home-assistant.io/integrations/homekit_controller/

**Comment by TheFitzZZ** [comment]
For me it's just a switch, and it reports a 20 min timeout when enabled. Maybe just a difference between the two systems :-) Can work around it easily so I don't mind.

**Comment by ApplesandPears** [comment]
@TheFitzZZ Okay. ;-)
