### ISSUE TITLE
Error 'no location found'

### ISSUE THREAD

**Issue by ebolly** [py-smart-gardena/hass-gardena-smart-system#117]
Hello, 

Using the 1.0.0b900 version I can't make the integration run correctly.

Even after uninstall/reboot/installing, integrationkeep failing with this error (and yep, I've created new Application and APIs)

`Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:89
Integration: Gardena Smart System integration ([documentation](https://github.com/py-smart-gardena/hass-gardena-smart-system), [issues](https://github.com/py-smart-gardena/hass-gardena-smart-system/issues))
First occurred: 19:39:03 (4 occurrences)
Last logged: 19:48:09

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 48, in async_setup_entry
    await gardena_system.start()
  File "/config/custom_components/gardena_smart_system/__init__.py", line 89, in start
    raise Exception("No locations found")
Exception: No locations found`

I've also discoverd this error in HA logs

Logger: gardena.smart_system
Source: /usr/local/lib/python3.9/site-packages/gardena/smart_system.py:125
First occurred: 19:39:03 (4 occurrences)
Last logged: 19:48:09

404 : {r['errors'][0]['title']} - {r['errors'][0]['detail']}

any idea ?

**Comment by grm** [comment]
Hello,

Strange behaviour.
Do you have multiple locations configured in the app ?
And do you have check the boxes when creating the client id on the husqvarna website ?

Grm

**Comment by ebolly** [comment]
oh god... My apologies, using the wrong userid/password. 
Better with the correct one.

Everything is fine, sorry again.
