### ISSUE TITLE
Cannot add integration. Form is cleared

### ISSUE THREAD

**Issue by sljdhl** [py-smart-gardena/hass-gardena-smart-system#118]
I have installed this through HACS, restarted HA and when I try to add the integration I get a popup for:
* Email ( no information about this in the installation guide)
* Password(is this secret key or account password?)
* Application key/Client ID

Authentication API and the GARDENA smart system API is added.
When I add the information from the husqvarna developer site, the form is cleared and nothing happens.

Im on HA 2022.6.5 right now, tried some older versions before but I have the same issue.

**Comment by IXArcanumXI** [comment]
Husqvarna changed the authentication method. Completely uninstall the integration through HACS and install the newest BETA-Version (1.0.0b900). The new login-popup asks for Application Key and Application Secret.

**Comment by sljdhl** [comment]
> Husqvarna changed the authentication method. Completely uninstall the integration through HACS and install the newest BETA-Version (1.0.0b900) of the integration. The new login-popup asks for Application Key and Application Secret.

Oh! That solved it thank you
