### ISSUE TITLE
'WaterControl' object has no attribute 'last_error_code'

### ISSUE THREAD

**Issue by browetd** [py-smart-gardena/hass-gardena-smart-system#119]
I got this error message recently (using the last version of the integration (1.0.0-0b901) and last version of Hass.OS as well as Core (2022.6.6)):

`2022-06-15 09:04:12 ERROR (MainThread) [homeassistant.components.switch] gardena_smart_system: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    await task
  File "/config/custom_components/gardena_smart_system/switch.py", line 84, in async_update
    self._error_message = self._device.last_error_code
AttributeError: 'WaterControl' object has no attribute 'last_error_code'`

**Comment by browetd** [comment]
This error is preventing HA to start correctly... It is stopped around 5 minutes before continuing after the following message:

[homeassistant.bootstrap] Setup timed out for bootstrap - moving forward

**Comment by browetd** [comment]
The only way to have a rapid HA start process is to disable the integration (even disabling the watercontrol entities did not fix the slow HA startup)

**Comment by grm** [comment]
Thanks i all have a look into it !

**Comment by keyb-on-ice** [comment]
Same for me. 

[homeassistant.bootstrap] Setup timed out for bootstrap - moving forward.
Thanks for your great work!

**Comment by browetd** [comment]
I noticed this morning that the switch entity associated with the pump "Gardena Smart Pressure Pump" is even not created, so no way to control the pump with HA anymore...  Thank you for your work !

**Comment by browetd** [comment]
I made some additional investigations... I removed the error in switch.py by storing an empty error code instead of looking for this "last_error_code"... So even without error (the switch for the water pump is created), I still have a "timeout for bootstrap" at HA startup, this makes me think that the error and the bootstrap are probably two separated problems.

**Comment by browetd** [comment]
As I mentionned, I fix the error for Water_Control device being in error.  The problem is coming from "py-smart-gardena" library (see the following link):

https://pypi.org/project/py-smart-gardena/

There is effectively no "last_error_code" for "water_control" device...  So what I did (as my device is in ERROR), I changed the following code in switch.py of the integration (lines 81 to 84):

`        if state in ["WARNING", "ERROR", "UNAVAILABLE"]:
            _LOGGER.debug("Water control has an error")
            self._state = False
            self._error_message = self._device.last_error_code`

by this:

`        if state in ["WARNING", "ERROR", "UNAVAILABLE"]:
            _LOGGER.debug("Water control has an error")
            self._state = False
            type = self._device.type
            if type in ["WATER_CONTROL"]:
                self._error_message = "UNKNOWN ERROR"
            else:
                self._error_message = self._device.last_error_code`

Now the switch for my water pump is created with an Error code "UNKNOWN ERROR" as an attribute.

Unfortunately the following error remains (removing the Gardena integration, removes also this problem):

2022-07-02 18:42:28 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for bootstrap - moving forward

But this is above my level of competency... 

Nevertheless, the integration is working fine (for 24hours but that's another issue).

**Comment by grm** [comment]
Thx for the search of the issue @browetd !

I'll have a look into it now !

**Comment by grm** [comment]
It will be fixed in the next release (hopefully sonn)

**Comment by grm** [comment]
The fix has just been released in the 1.0.0-0b902 version.

Please tell me if it is working or not please.

**Comment by browetd** [comment]
Working for me !  Thanks !!!!
