### ISSUE TITLE
Websocket lost connection, no more updates

### ISSUE THREAD

**Issue by osks** [py-smart-gardena/hass-gardena-smart-system#12]
I noticed that my sensors had old values and found this in the Home Assistant log (developer tool GUI):

> Logger: websocket
Source: util/thread.py:20
First occurred: May 31, 2020, 7:50:26 PM (1 occurrences)
Last logged: May 31, 2020, 7:50:26 PM
>
> error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x7f17043d5850>>: 403 Client Error: Forbidden for url: https://api.smart.gardena.dev/v1/websocket

The last sensor update was from around that time. It seems it doesn't restart the websocket after that error.

**Comment by northpower25** [comment]
@osks could you implement the gardena testtool from here (https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/5#issuecomment-636923978) into the integration with an binary sensor for the linktest to see fast cloud problems? Make its sense or is it possible to implement an fallback mechanism for an local connection without cloud?

**Comment by grm** [comment]
@northpower25 : which testtool are you talking about ?

**Comment by northpower25** [comment]
I think an livelink As binary sensor make sans to prevent us for questions about issues that depending on Network or cloud problems on the gardena side. So that the user easyly check gardena cloud reachable or not

**Comment by grm** [comment]
Ok, including a full swagger won't be doable easily (and i don't think we want to ;).
But maybe we could think of something like a service checker which just test if the service is online or not.

**Comment by grm** [comment]
I am looking into this issue.
I have launch the script on a spare computer and the script is now running for 16hours+ with a refreshed token every hour.
Maybe the issue is more when gardena restarts/update their system, we are not retrying to reconnect indefinitely and we should make this part more robust to retry every x (probably 1) minute to reconnect to the API. 
I will have a look into it.

**Comment by northpower25** [comment]
@osks please check this solution for the issue and give us a feedback if it works -> https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/5#issuecomment-638851191

**Comment by grm** [comment]
I am not sure it is related to the same issue (it is not an access token issue).
Please keep this ticket open as I still have evolutions to do ine the library to robustify it :)

Jérémie

**Comment by dk1305hb** [comment]
I received this message when my sensors no longer received an update

2020-06-04 15:11:24 ERROR (Thread-495) [gardena.smart_system] error : ping/pong timed out
2020-06-04 15:11:25 INFO (Thread-495) [gardena.smart_system] Connection close to gardena API
2020-06-04 15:11:25 INFO (Thread-495) [gardena.smart_system] Restarting websocket
2020-06-04 15:11:27 ERROR (Thread-495) [websocket] error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x7fadb04a0ed0>>: 504 Server Error: Gateway Timeout for url: https://api.smart.gardena.dev/v1/websocket

**Comment by grm** [comment]
I updated the library yesterday and I am currently testing the fix. It
behaves zelle for now. I will try to make a release this week end !

Grm

**Comment by grm** [comment]
The new release 0.1.0 should fix this issue.
Do not hesitate to re-open the ticket if you still have issue after upgrading.

**Comment by dk1305hb** [comment]
I still received a service stop.

`2020-06-08 12:44:18 ERROR (Thread-55) [gardena.smart_system] error : ping/pong timed out
2020-06-08 12:44:21 INFO (Thread-55) [gardena.smart_system] Connection close to gardena API
2020-06-08 12:44:21 INFO (Thread-55) [gardena.smart_system] Restarting websocket
2020-06-08 12:44:52 ERROR (Thread-55) [websocket] error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x7ff59836a290>>: 503 Server Error: Service Unavailable for url: https://api.smart.gardena.dev/v1/websocket
`
`xyz:hass-gardena-smart-system xyz$ git log
commit 748c5c0862a9ae98a72c0212813cbb54b83fc15a (HEAD -> master, origin/master, origin/HEAD)
Author: Grm <grm.klein@gmail.com>
Date:   Sun Jun 7 03:02:39 2020 +0200
`
Many thanks for your updates.
