### ISSUE TITLE
Setup failed

### ISSUE THREAD

**Issue by paradix** [py-smart-gardena/hass-gardena-smart-system#120]
After updating to Home Assistant Core 2022.6.6 and Gardena Smart System 1.0.0-0b901 I get following error

Logger: homeassistant.setup
Source: setup.py:162
First occurred: 11:46:13 (1 occurrences)
Last logged: 11:46:13

Setup failed for custom integration gardena_smart_system: Unable to import component: No module named 'authlib'

**Comment by grm** [comment]
Could you try to restart the proces or home assistant ?
Did you find any solution or do you have any more info ?

**Comment by paradix** [comment]
I finally solved it yesterday by manually installing the missing package via pip in my home assistant venv.
