### ISSUE TITLE
Where do you need to enter the API Keys after installation

### ISSUE THREAD

**Issue by KarmCraft** [py-smart-gardena/hass-gardena-smart-system#122]
Admittedly, I'm a HA newby. After adding the Gardena HACS Integration I'm stuck as after Point 6) it does not say where to insert the API Keys.
Thanks for any advice.

**Comment by SNoof85** [comment]
Go to the integrations panel : https://my.home-assistant.io/redirect/integrations/
Then down right corner, click on Add, looks for gardena, select it, then wait for the config and it will ask you app key and secret app key.

**Comment by KarmCraft** [comment]
Thank you. When I do this an error appears after a long wait:

![image](https://user-images.githubusercontent.com/15261206/175793923-62e0f20a-ff96-4d9e-b828-2a9715daafbe.png)

Translated it means something like "Config flow couldn't be loaded: undefined"

**Comment by Cyberwizzard** [comment]
I have the same issue, after finding this thread I figured out where the API key needs to be inserted, but upon entering the information, I just get the same login panel again.

Is this currently working for anyone? Is there a debug log somewhere?

**Comment by SvenBre** [comment]
No, I had the latest release installed through HACS, version 0.2.3. I was thinking this thread is about that version. Now I uninstalled and got 1.0.0-0b901. This one is working. It does not ask vor email and password, but for application key and secret. Thanks for pointing me at this.

**Comment by grm** [comment]
Thx  @Paul-Vdp for helping on this !
I just released a new version marked as stable (even if it is not a real one ... ) in order to prevent this kind of issue in the future (as the stable release is kot wotking anymore !
