### ISSUE TITLE
Gardena not available

### ISSUE THREAD

**Issue by bartdetre** [py-smart-gardena/hass-gardena-smart-system#124]
Hi,

Since a few day my Gardena Integration is not working anymore and entities show up as not available.
This is the logfile:

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:44
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 08:32:17 (1 occurrences)
Last logged: 08:32:17

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 44, in async_setup_entry
    client_secret=entry.data[CONF_CLIENT_SECRET],
KeyError: 'client_secret'

I think it's a problem with the "client sercret" but i didn't change anything. Problem started after update of the Gardena integration in HACS.
Can anyone help please?

Kind regards

**Comment by bartdetre** [comment]
Found the solution for this in the closed items!

**Comment by grm** [comment]
Good to know.
Sorry for the delay in the answer :)
