### ISSUE TITLE
Failure to start with Home Assistant 2022.7.0

### ISSUE THREAD

**Issue by mfschumann** [py-smart-gardena/hass-gardena-smart-system#125]
After updating to Home Assistant 2022.7.0 I get the following error and no gardena sensors work anymore. I suspect this to be related to the upgrade to python 3.10 in Home Assistant 2022.7.0.

`Setup failed for custom integration gardena_smart_system: Unable to import component: No module named 'gardena'`

I am happy to provide more information if needed.

**Comment by strutings** [comment]
Tried a manual installation of py-smart-gardena?

**Comment by mfschumann** [comment]
After manually installing py-smart-gardena in Home Assistant's container (named hass) by running 

`podman exec -it hass pip install py-smart-gardena` 

and redownloading the integration using HACS it starts fine again.

Thanks for the quick help!

**Comment by mfschumann** [comment]
Reopening the issue because the manual installation is only a temporary workaround: Whenever the container is recreated, the problem appears again.

**Comment by mfschumann** [comment]
I think the problem could be caused by a regression in `homeassistant.util.package` which I reported in [this issue](https://github.com/home-assistant/core/issues/74597). So presumably there is not much that can be done on the end of this integration.

**Comment by nanosonde** [comment]
I assume that this issue is obsolete since HA 7.4 as this was merged: https://github.com/home-assistant/core/pull/74922

**Comment by mfschumann** [comment]
Yes, I can confirm that HA 7.4 fixes the issue for me. Note however that the issue vanished only after an additional restart of Home Assistant after the restart during upgrade.
