### ISSUE TITLE
Problem with installation the integration again

### ISSUE THREAD

**Issue by kommis** [py-smart-gardena/hass-gardena-smart-system#147]
Hello,

can you help me with the integration. It works not at the moment.

It have installed the newest one: [GitHub - py-smart-gardena/hass-gardena-smart-system: Home Assistant custom component integration for Gardena Smart System 1](https://github.com/py-smart-gardena/hass-gardena-smart-system)

Husquarna Developer:
![grafik](https://user-images.githubusercontent.com/95351671/191450690-1bc849c1-3df2-49fd-b304-f47085ca0c1c.png)

![grafik](https://user-images.githubusercontent.com/95351671/191450758-757c5cdf-ddc8-4b06-9915-ea18aa1de463.png)

![grafik](https://user-images.githubusercontent.com/95351671/191458321-bd0145c4-1f12-4531-bc58-d7e8eae98921.png)

thanks for your help!

best regards

**Comment by kommis** [comment]
i have also entered the username and password from husquarna developer:

![grafik](https://user-images.githubusercontent.com/95351671/191461744-07b4d1e7-50f5-4384-82ab-28f705040adf.png)

**Comment by neuhausf** [comment]
Same here - however I did not try to reauthenticate.
![image](https://user-images.githubusercontent.com/7963239/191703847-4501a2e8-3887-4631-a35c-f0865ed9d93c.png)

**Comment by kommis** [comment]
Have anybody a solution? I need this Integration for my automation! Or do you need some extra Information? Thanks! Wish you a nice evening!

**Comment by kommis** [comment]
The Support is not good here! I wait one month for one answer!

**Comment by neuhausf** [comment]
@kommis my problem eventually solved after I disabled and reenabled the component. But I had a different error code (401).

**Comment by kommis** [comment]
I have also solved the Problem now. I have reset all datas

The gardena App
New Account in the App with different Email Adress
Then install the Integration New

And now the Integration works in HA
