### ISSUE TITLE
Can not find integration

### ISSUE THREAD

**Issue by Fredrik13** [py-smart-gardena/hass-gardena-smart-system#16]
I have copied the files from "gardena_smart_system" to my custom components/gardena_smart_system, but can not find the integration under "configuration....integrations". I have searched but it does not show up. Any ideas what I do wrong?

**Comment by northpower25** [comment]
Do you have restart HA after this you shut find it after this unter der Plus symbol 
![D48FDDA8-2585-47C8-A118-9650A97978E8](https://user-images.githubusercontent.com/36472486/83749159-8c0f2f80-a663-11ea-862c-1a30aa7c303e.jpeg)
![1A2A94F5-09F6-4CDE-AD38-3895A9DA0F20](https://user-images.githubusercontent.com/36472486/83749161-8ca7c600-a663-11ea-87e9-5c778fae9a97.jpeg)

**Comment by Fredrik13** [comment]
Yes several restarts, and then I go to configuration and integrations and search. I can not even find it here: https://www.home-assistant.io/integrations/

**Comment by ApplesandPears** [comment]
Try it via HomeKit-Controller... This works currently.

Go to "Configuration / Einstellungen" then to "Integrations / Integrationen", click the "+" in the bottom right corner, Search for "HomeKit Controller", Click on it and then choose from the drop down menu the Gardena Smart System. Enter the HomeKit code, printed on the back of the Gardena Smart Gateway - et voilà the Gardena Bridge including all Switches and Sensors is now available in Home Assistant.

From there, if you're an iOS User, you can expose those devices to the HA HomeBridge. 

![image](https://user-images.githubusercontent.com/56008284/83750661-e5785e00-a665-11ea-9abd-15387f43de0f.png)

**Comment by grm** [comment]
Have you tried install it through HACS ?

**Comment by Fredrik13** [comment]
> Have you tried install it through HACS ?

No. Hacs broke when I updated to latest HA. Need to fix that first 😉

**Comment by Fredrik13** [comment]
> Try it via HomeKit-Controller... This works currently.
> 
> Go to "Configuration / Einstellungen" then to "Integrations / Integrationen", click the "+" in the bottom right corner, Search for "HomeKit Controller", Click on it and then choose from the drop down menu the Gardena Smart System. Enter the HomeKit code, printed on the back of the Gardena Smart Gateway - et voilà the Gardena Bridge including all Switches and Sensors is now available in Home Assistant.
> 
> From there, if you're an iOS User, you can expose those devices to the HA HomeBridge.
> 
> ![image](https://user-images.githubusercontent.com/56008284/83750661-e5785e00-a665-11ea-9abd-15387f43de0f.png)

I do not have any Homekit codes on my Gardena hub. It is 2 years old, and maybe before homekit was a thing for Gardena

**Comment by Fredrik13** [comment]
> > Have you tried install it through HACS ?
> 
> No. Hacs broke when I updated to latest HA. Need to fix that first 😉

I installed HACS, but can not find it there either. Strange.....

**Comment by northpower25** [comment]
@Fredrik13 have you add the repo to your custom repositorys of HACS? 

„ Use "https://github.com/py-smart-gardena/hass-gardena-smart-system" as URL for a new HACS custom repository.“

**Comment by Fredrik13** [comment]
> @Fredrik13 have you add the repo to your custom repositorys of HACS?
> 
> „ Use "https://github.com/py-smart-gardena/hass-gardena-smart-system" as URL for a new HACS custom repository.“
> 
> @grm @osks do we have a chance to get this integration into the HACS integration catalogue?

I tried but I might not done it right. Where and how do I do that?

**Comment by Fredrik13** [comment]
![image](https://user-images.githubusercontent.com/58874757/83939825-2eecb880-a7e0-11ea-918d-e8a649cf3b9f.png)

**Comment by northpower25** [comment]
i've checkt this for me it works
1. go to HACS in HA
2. select "Custom Repository" over the 3-Bullet top-right menu
![image](https://user-images.githubusercontent.com/36472486/83941207-dfab8580-a7e9-11ea-82de-74bd2da95a20.png)
3. copy the following URL https://github.com/py-smart-gardena/hass-gardena-smart-system in the "Add custom repository URL" field and choose " integration in the "category" pull-down-menu
![image](https://user-images.githubusercontent.com/36472486/83941268-67918f80-a7ea-11ea-9762-222e47108721.png) click on the "Add" button
3. now it shut shows like the following Screenshot and the Gardena Integration repo is aktive in your HACS enviroment
![image](https://user-images.githubusercontent.com/36472486/83941302-90198980-a7ea-11ea-8d21-488d76c4d6fd.png)
4. now you have to install it in HACS
![image](https://user-images.githubusercontent.com/36472486/83941356-f1415d00-a7ea-11ea-9cd3-346f1eef9e94.png)
![image](https://user-images.githubusercontent.com/36472486/83941371-10d88580-a7eb-11ea-9f76-cdf05e379bf9.png)
in this step the files freom the repo are copyed to the custom integration folder of your HA installation. if an update on the github repo is published you see in HACS this and can update easyly

5. if you have installed in HACS you habe to setup the integration in HA settings with your credentials from gardena and the Application Key from the Gardena/Husquarna API.

I hope that helps you to get it to work.

**Comment by Fredrik13** [comment]
Northpower thank you for the detailed explanation. It worked and I now have my mower integrated in HA :-) I missed the part how to add custom respositories, but now I know

**Comment by northpower25** [comment]
Thank for your feedback. 👍🏻 Could you please close this issue if it working for you. 😉
