### ISSUE TITLE
Water Control ambient temperature sensor

### ISSUE THREAD

**Issue by lukasvermeer** [py-smart-gardena/hass-gardena-smart-system#17]
It seems that the Water Control unit in my garden has a secret ambient temperature sensor which does not show up in the Gardena App. I suspect this sensor is in the device to enable frost warnings.

When using the [OpenHAB Gardena binding](https://github.com/openhab/openhab-addons/tree/2.5.x/bundles/org.openhab.binding.gardena) it is able to read and display the "Ambient Temperature" data.

<img width="487" alt="Screenshot 2020-06-04 at 17 03 45" src="https://user-images.githubusercontent.com/552432/83773922-6abf3b00-a685-11ea-8084-d1d5598a9258.png">

Not sure how the implementation of this integration for Home Assistant is different from the OpenHAB binding, but the same sensor does not show up.

<img width="1007" alt="Screenshot 2020-06-04 at 17 04 03" src="https://user-images.githubusercontent.com/552432/83773916-68f57780-a685-11ea-9628-715591fc4ac2.png">

Perhaps this sensor could be added here too?

**Comment by northpower25** [comment]
@lukasvermeer the sensor you request is in the integration. In addition there is an Soil temperatur sensor 😉
![C049B4D2-E56D-459A-983E-37643BEC0B7C](https://user-images.githubusercontent.com/36472486/83787287-db6d5400-a693-11ea-932a-1f0d7e1d3399.png)
![55810DF8-F7F5-4636-8D4E-66AB0ACF8781](https://user-images.githubusercontent.com/36472486/83787292-ddcfae00-a693-11ea-92b1-3b97c71d811d.png)
![15B91163-D53A-4CD6-A293-5062DE879DAA](https://user-images.githubusercontent.com/36472486/83787295-de684480-a693-11ea-8c82-f83ec5e8005d.png)

**Comment by lukasvermeer** [comment]
@northpower25 Apologies if my description was unclear. Your screenshots seem to show screens for a [Gardena Smart Sensor](https://www.gardena.com/nl/producten/bewateren/besproeiingscomputers/gardena-smart-sensor/967044801/)? My query was for a [Gardena Smart Water Control](https://www.gardena.com/nl/producten/bewateren/besproeiingscomputers/gardena-smart-water-control/967045101/).

**Comment by northpower25** [comment]
@grm @osks do you see an possibility for this?

**Comment by grm** [comment]
Hello,

I did not find this information in the raw messages .. I started have a look at the source code but I did not find the source of the info yet.
Does this temperature seems the right one ?

Grm

**Comment by lukasvermeer** [comment]
> Does this temperature seems the right one ?

Not sure I am interpreting your question correctly, @grm, but yes, the temperature reported seems reasonable.

Here is a few days of data from the sensor (in sheltered location adjacent the house) compared against OpenWeatherMap:

<img width="1746" alt="Screenshot 2020-06-08 at 09 24 32" src="https://user-images.githubusercontent.com/552432/84003189-ebbe5100-a969-11ea-8536-2e6eb922bc39.png">

**Comment by osks** [comment]
The temperature sensor in the Water Control is not exposed in the official API. I guess the OpenHAB is using the inofficial/reversed-engineered API.

So I'm afraid this is not something we can add until Gardena/Husqvarna adds it to the official API.

**Comment by lukasvermeer** [comment]
Clear and understood. It will not be hugely missed. Thanks for checking, @osks.
