### ISSUE TITLE
2024.1 deprication warning for VACCUUM_COMPONENT

### ISSUE THREAD

**Issue by ChristophCaina** [py-smart-gardena/hass-gardena-smart-system#186]
2024.1 will throw a deprication warning for the following import:

```
from homeassistant.components.vacuum import (
    StateVacuumEntity,
    SUPPORT_BATTERY,
    SUPPORT_RETURN_HOME,
    SUPPORT_STATE,
    SUPPORT_STOP,
    SUPPORT_START,
    STATE_PAUSED,
    STATE_CLEANING,
    STATE_DOCKED,
    STATE_RETURNING,
    STATE_ERROR,
    ATTR_BATTERY_LEVEL,
)
```

The `SUPPORT_***` features for Vacuum will be depricated and should be replaced by `VacuumEntityFeature`
https://developers.home-assistant.io/docs/core/entity/vacuum/#supported-features

**Comment by grm** [comment]
Thx for the report, I'll have a look into it asap :)

**Comment by grm** [comment]
Should be good in version 1.1.0-rc3 !
can you confirm ?

**Comment by timbba80** [comment]
I did install 1.1.0-rc3 and at least on my end it's still giving the same warning. 

While checking the changes with 1.1.0-rc3, it seems that the vacuum.py is not updated (last update Jan 23, 2023 with merging pr #103

[https://github.com/py-smart-gardena/hass-gardena-smart-system/blob/1.1.0-rc3/custom_components/gardena_smart_system/vacuum.py](url):

from homeassistant.components.vacuum import (
    StateVacuumEntity,
    SUPPORT_BATTERY,
    SUPPORT_RETURN_HOME,
    SUPPORT_STATE,
    SUPPORT_STOP,
    SUPPORT_START,
    STATE_PAUSED,
    STATE_CLEANING,
    STATE_DOCKED,
    STATE_RETURNING,
    STATE_ERROR,
    ATTR_BATTERY_LEVEL,

**Comment by grm** [comment]
Ok !

**Comment by albaintor** [comment]
Hi is it the same warning as the one that I have:
`Entity None (<class 'custom_components.gardena_smart_system.vacuum.GardenaSmartMower'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <VacuumEntityFeature.STOP|RETURN_HOME|BATTERY|STATE|START: 12376>, please create a bug report at https://github.com/py-smart-gardena/hass-gardena-smart-system/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation`

**Comment by grm** [comment]
Can you give it another try with version 1.1.1.-rc3 ?

**Comment by ElBalsero** [comment]
Hi,
I have tried v1.1.1.-rc3 with 2024.4.0 and I am not getting the warning anymore.
It seems to be solved, from my point of view.
