### ISSUE TITLE
2024.01 Deprecation Warning for DEVICE_CLASS_CONNECTIVITY

### ISSUE THREAD

**Issue by pschyrembel258** [py-smart-gardena/hass-gardena-smart-system#188]
Logger: homeassistant.components.binary_sensor
Source: helpers/deprecation.py:204
Integration: Binärsensor (documentation, issues)
First occurred: 14:07:42 (2 occurrences)
Last logged: 14:07:42

DEVICE_CLASS_CONNECTIVITY was used from gardena_smart_system, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.CONNECTIVITY instead, please create a bug report at https://github.com/py-smart-gardena/hass-gardena-smart-system/issues

**Comment by grm** [comment]
Thank you for the report and the PR !
