### ISSUE TITLE
Integration is not starting after instalaltion from GitHub

### ISSUE THREAD

**Issue by SukaleA** [py-smart-gardena/hass-gardena-smart-system#190]
I'm using HomeAsisstant core (German Installation), installed on a Synology NAS-Server. After downloading the Gardena Smart Home Integration, I wanted to staret configuring it adding thwe integration in Services.
There, it started the configuration, but ended it soon with the following error messeage:

"**Fehler
Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}**" 

Home Assistant is installed in "/volume1/@appdata/homeassistant" and the gardena integration has been downloaded to 
"**/volume1/@appdata/homeassistant/config/custom_components/gardena_smart_system**"

I have created the "Application Secret" in the Husquarna Developers Portal, but it was not even possible to enter it somewhere, because the installation window did not start.

What shall I do ?

Regards
Andreas

**Comment by grm** [comment]
Have you try to install it from HACS ?

**Comment by SukaleA** [comment]
Yes, that's why I contacted you

Sent from MailDroid

-----Original Message-----

**Comment by grm** [comment]
Could you give it another try with version 1.1.0-rc3 ?

**Comment by SukaleA** [comment]
Sure, will be back on Monday ... send you feedback soon..
Many thanks so far
Andre
as

Sent from MailDroid

-----Original Message-----

**Comment by helmut-hackl** [comment]
> Have you try to install it from HACS ?

Tested and works like a charm again! Thank you for fixing this and thank you for your time. May I buy you a coffee in any way ...

**Comment by helmut-hackl** [comment]
> Have you try to install it from HACS ?

Tested and works like a charm again! Thank you for fixing this and thank you for your time. May I buy you a coffee in any way ...

**Comment by mercslkamg** [comment]
Saw the update today. Great everything ok now with CORE 2024.2.1
Many thanks for the fix.

**Comment by SukaleA** [comment]
Works fine now, thanks a lot 
Andreas

Sent from MailDroid

-----Original Message-----
