### ISSUE TITLE
Hello, is it possible to fix this for next year's version

### ISSUE THREAD

**Issue by Thunderbird1982** [py-smart-gardena/hass-gardena-smart-system#191]
Entity None (<class 'custom_components.gardena_smart_system.vacuum.GardenaSmartMower'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <VacuumEntityFeature.STOP|RETURN_HOME|BATTERY|STATE|START: 12376>, 

thanks Thunderbird

**Comment by eikowagenknecht** [comment]
With link to the announcement:

```
 Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1524
First occurred: 15:27:32 (1 occurrences)
Last logged: 15:27:32
Entity None (<class 'custom_components.gardena_smart_system.vacuum.GardenaSmartMower'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <VacuumEntityFeature.STOP|RETURN_HOME|BATTERY|STATE|START: 12376>, please create a bug report at https://github.com/py-smart-gardena/hass-gardena-smart-system/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
```

**Comment by grm** [comment]
Thx, a MR has been don, I still have to releease it. :)

**Comment by grm** [comment]
Should be fixed !
I had issues yesterday with travisci which does not work as expected anymore.
I migrated to github actions for building the underlying library py-smart-gardena.

I just release a 1.1.0-rc3 version (in beta) that should solve the issue.
