### ISSUE TITLE
Gardena Smart System Integration startet nicht mehr 

### ISSUE THREAD

**Issue by hito1969** [py-smart-gardena/hass-gardena-smart-system#195]
Unter HA Core 2024.2.0 und 2024.2.1 startet Gardena Smart System Integration nicht mehr

**Comment by crandler** [comment]
See https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/192

**Comment by grm** [comment]
Fixed In 1.1.0-rc3

**Comment by grm** [comment]
Can you test ?
