### ISSUE TITLE
Gardena - Needs attention

### ISSUE THREAD

**Issue by Fauch123456789** [py-smart-gardena/hass-gardena-smart-system#202]
Hello,
I had to reinstall the Gardena integration after a Gardena hub reset. While it was working in the past,  now I have no components detected and a message stating «  needs attention - failed to setup ». I tried several times with the same result. I’m a newbie in HA and don’t know if it’s a bug caused by a previous install or something else, I don’t know how to investigate the problem. Would anyone be kind enough to suggest a path to resolution? Thanks in advance.

**Comment by MikeLehnitz** [comment]
I have the same problem. Integration recognizes everything. After restarting HA, the error message appears.
Version 1.1.0 
Core 2024.3.0
Supervisor 2024.02.1
Operating System 12.0
Frontend 20240306.0
Log:
Logger: homeassistant.config_entries
Quelle: config_entries.py:504
Erstmals aufgetreten: 14:25:07 (1 Vorkommnisse)
Zuletzt protokolliert: 14:25:07

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)

**Comment by kizio1000** [comment]
For me it's every time HA starts but I found workaround. Disable integration and right after enable it again and it works.

**Comment by CHTHSCH** [comment]
> For me it's every time HA starts but I found workaround. Disable integration and right after enable it again and it works.

I have the same problem and use the same work around.

Using Home Assistant Yellow
Core 2024.3.1
Supervisor 2024.03.0
Operating System 12.1
Frontend 20240307.0

**Comment by Elle4u** [comment]
Same to me. I also have to disable/enable after every restart of HA.

**Comment by grm** [comment]
there is a new release 1.1.1-rc2 in beta.
Can you give it a try ?

Thanks,
grm

**Comment by guennikasse** [comment]
Now it works
Thanks
release 1.1.1-rc3

**Comment by Fauch123456789** [comment]
It works for me also. Also, I am ashamed of myself, I understand why it was not working when reinstalling the integration: in the password field I used my gardena password, not the second key the Husqvarna provides… I’ll know for next time.

**Comment by Elle4u** [comment]
It also works for me, now. Thanks for the fast support!

**Comment by clipse2004** [comment]
Hey Guys,

and it also worked for you After HA Restart? 
I still have the same problem after a restart. Even a new installation did not help :/

**Comment by CHTHSCH** [comment]
The patch seems not to be released yet.
When re-installing, I still get 1.1.0 - and in there the problem is not fixed
When will the new version 1.1.1 be released?

**Comment by kizio1000** [comment]
On my system RC3 seams to be working. After update and system restart integration was loaded correctly.

**Comment by kizio1000** [comment]
After all not really fixed. Today restart of HA (2x) proven integration still not starting correctly though disabling and enabling integration still fix problem till next restart of HA
