### ISSUE TITLE
Supported Feature will be removed in 2025.1

### ISSUE THREAD

**Issue by say1897** [py-smart-gardena/hass-gardena-smart-system#203]
Logger: homeassistant.helpers.entity
Quelle: helpers/entity.py:1597
Erstmals aufgetreten: 19:08:31 (1 Vorkommnisse)
Zuletzt protokolliert: 19:08:31

Entity None (<class 'custom_components.gardena_smart_system.vacuum.GardenaSmartMower'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <VacuumEntityFeature.STOP|RETURN_HOME|BATTERY|STATE|START: 12376>

Reference: https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by grm** [comment]
I prepared a new version a few days ago and released the version 1.1.1-rc2.
Can you check everything is fine on your side ?

Thanks,
grm

**Comment by say1897** [comment]
Is this a beta version?

So far, I've only installed the official releases. Currently, version 1.1.0 is installed. I haven't been notified of any updates yet.

**Comment by grm** [comment]
Yes it is a beta version :)

**Comment by grm** [comment]
And the version is now 1.1.1-rc3

**Comment by say1897** [comment]
So I have to delete the stable version and install the beta for testing?

**Comment by grm** [comment]
You just have to activate beta version  in hacs for this integration and it
should work.

You can deactivate beta version  once the full release is out.

**Comment by say1897** [comment]
![image](https://github.com/py-smart-gardena/hass-gardena-smart-system/assets/157413310/880bfd88-3152-4795-b89c-49e3c0c448b6)
OK! I downloaded, installed, and restarted the beta. Currently, no error message is visible in the log.
