### ISSUE TITLE
Platforms switch and vacuum could not be set up

### ISSUE THREAD

**Issue by malundqvist** [py-smart-gardena/hass-gardena-smart-system#24]
I installed through HACS, fixed app key from Husqvarna and added the integration from ui without problem. However, I get a error message that switch and vacuum entities could not be set up and also no entities for these. I have tried removing the integration and re-adding it without luck. Is there something else in the process of adding this integration that I have missed? Have made a couple of restarts including restart between installing component and adding integration. Running Core 0.107.4

<img width="488" alt="Skärmavbild 2020-06-07 kl  20 24 49" src="https://user-images.githubusercontent.com/46251256/83976928-7ae14f80-a8fd-11ea-8038-a37f5292aeab.png">

<img width="1111" alt="Skärmavbild 2020-06-06 kl  23 43 19" src="https://user-images.githubusercontent.com/46251256/83976932-82a0f400-a8fd-11ea-99c1-4f7f4283abab.png">

**Comment by grm** [comment]
Hello,

You shoud configure everything from the UI.

Once installation is done in hacs, you should go to 'Configuration (on the left panel in home assistant' -> Integrations then click the + sign' directly in home assistant config. Choose gardena from the integrations list and you will be then prompted for your login/passwrd and application id.

Grm

**Comment by malundqvist** [comment]
Thanks for the reply @grm 
I have done it exactly as you say, however the first time I added the integration, I had made the Husqvarna app and received the application key but missed the "connect to..."-part. Once connected, I removed the integration and re-added it and I do get sensor entities for all sensors in Gardena Smart Sensor, as well as battery level for Gardena Mower and Water Control. But switch and vacuum entities won't show up and also the new binary sensor you added also gives an error now (was not included in the version I installed yesterday I guess). I have not done any manual config at all regarding Gardena. I just now redid the whole thing by removing integration and uninstall of component, and then adding it back as you described above, but no luck. Do you have any tips?

**Comment by grm** [comment]
Are you using a recent version of home-assistant ?

**Comment by malundqvist** [comment]
I’m currently using 0.107.4. It’s time to update though so I can try that.

**Comment by grm** [comment]
Indeed -_-

Le lun. 8 juin 2020 à 09:14, malundqvist <notifications@github.com> a
écrit :

**Comment by osks** [comment]
You need to upgrade. Version 0.110.0 or newer is required.

**Comment by osks** [comment]
This is specified in hacs.json, but perhaps HACS doesn't verify the version?

**Comment by osks** [comment]
Closing this as there is nothing to do here.
