### ISSUE TITLE
Clearify request, question and answer

### ISSUE THREAD

**Issue by MrUserY** [py-smart-gardena/hass-gardena-smart-system#33]
Can you clarify in the Information if this integration can be used without internet? In other words: if it has local control in a good DHCP network, but without internet. Maybe internet only for setup? I'm asking because I have no internet in a rural area and want to buy this Garenda system.

Answer on your question
"TODO
    Do we need support for more than one location? Should we make it
    possible to configure it?"

I don't know that answer! But for the !Privacy First! and remote networks without internet in rural area. Make shure it works without internet if that's isn't the case please! ;-)

**Comment by grm** [comment]
Hello MrUserY,

Unfortunately, the component won't work without internet. 
The Gardena component relies on an internet service provided by Gardena and we have no way to avoid this communication. Please contact gardena, so they can add an API directly in the smart gateway :)

Regards,
Grm
