### ISSUE TITLE
Frost warning

### ISSUE THREAD

**Issue by bjornta** [py-smart-gardena/hass-gardena-smart-system#35]
Would be nice to have the "frost warning".

I switched from "https://github.com/wijnandtop/home_assistant_gardena" repository where I could get this property.

**Comment by grm** [comment]
Hello Bjornta,

Unfortunately, this information is not available in the official API. Wijnandtop was using an unofficial reverse-engineered API.
We cannot do it until Gardena decides to add it in the official API, but when it will  be available, we will add it.

Thanks, Grm
