### ISSUE TITLE
Not working after 0.115

### ISSUE THREAD

**Issue by Johnyyy85** [py-smart-gardena/hass-gardena-smart-system#47]
Hi,

My gardena robot mower doesn't work anymore.
I has been working perfectly until I updated HA.
I get the following error message in my log:

Invalid config
The following integrations and platforms could not be set up:

gardena_smart_system.sensor
gardena_smart_system.switch
gardena_smart_system.vacuum
Please check your config.

**Comment by northpower25** [comment]
Do you have updated the integration to the last Version? There are an fix in place for the break after HA update to 0.115 
-> https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/43

**Comment by Johnyyy85** [comment]
I removed "unit" and now it works. i will try to close this thread.
thanks Northpower25!
