### ISSUE TITLE
With HA 0.116.1 the Sileno Mower breaks

### ISSUE THREAD

**Issue by northpower25** [py-smart-gardena/hass-gardena-smart-system#50]
After Update to HA 0.116.1 the Sileno Mower dosent work anymore with the integration. Everyelse (Sensors, Watering) work fine. 

I see no errors in the logs.

![9263E818-3A7A-45C2-9350-945839D788D1](https://user-images.githubusercontent.com/36472486/95653788-9ce11d80-0afb-11eb-8f49-c095d65d68a8.jpeg)

**Comment by tobiasbayer** [comment]
same here

**Comment by tobiasbayer** [comment]
Reinstallation of the plugin brought back the mower as `vacuum.sileno_2`.

**Comment by grm** [comment]
@northpower25 , same for you ? You needed a reinstallation ?

**Comment by northpower25** [comment]
> @northpower25 , same for you ? You needed a reinstallation ?

Yes after reinstallation of den integration it workes 👍🏻

**Comment by grm** [comment]
Ok, i close the issue :)
