### ISSUE TITLE
Gardena not showing up under integrations?

### ISSUE THREAD

**Issue by vandenbogerd** [py-smart-gardena/hass-gardena-smart-system#53]
I installed all needed files, in the correct (sub)folders.
I rebooted HASS.

I don't see the component appear under Integrations?

UPDATE: also tried installing via HACS; same issue...

**Comment by gidadavid** [comment]
same here runing on 2021.1.5

**Comment by markuswizard** [comment]
Same problem for me... running Home Assistant 2021.4.3

**Comment by GurkenTV** [comment]
Same here. Did anybody resolve it already?

**Comment by markuswizard** [comment]
> Same problem for me... running Home Assistant 2021.4.3

Did another try today and it showed up right away. Not sure what's actually solved it but it works perfectly. Now on Home Assistant 2021.4.6

**Comment by grm** [comment]
Hum, I will try to reproduce this issue on my side.

@vandenbogerd @gidadavid : do you still have the issue ?

**Comment by vandenbogerd** [comment]
No. I got it working in the end. But I don’t use HA anymore…

**Comment by MisterP64** [comment]
Same Problem today -  running version 2021.3.4

**Comment by MisterP64** [comment]
Today Gardena showed up. But installation ist not possible: failed in loading the configuration flow. (Der Konfigurationsfluss konnte nicht geladen der den). Thx for your help in advance

**Comment by tbloth** [comment]
Same here. I installed Gardena via HACS.
Core is running 2021.5.0.

Also an error is reported:
`2021-05-07 14:55:47 ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'gardena_smart_system'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'gardena_smart_system'`

**Comment by dgebhardt** [comment]
I have the same problem today, with core-2021.5.4.

Only thing I see in the logs:
`No 'version' key in the manifest file for custom integration 'gardena_smart_system'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'gardena_smart_system'`

**Comment by vandenbogerd** [comment]
Make sure you have the latest update; manifest.json does have "version" in it, since last month...
Download it manually, and overwrite it.

**Comment by dgebhardt** [comment]
Thanks for the hint. However, this warning had nothing to do with Gardena not showing up in the integrations section of HA after installing via HACS. This however was only the case in Safari. Searching for the integration with Chrome, I was able to locate and install it.

**Comment by alexfiftyfour** [comment]
Had the same problem. The fix to have the Gardena integration listed was simple: Reboot Home Assistant.

**Comment by grm** [comment]
Perfect !
