### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by sylviepipi** [py-smart-gardena/hass-gardena-smart-system#54]
Why asking username & password and not the application secret, is the password needed after installation ?

**Comment by lowrisk75** [comment]
same issue, trying to ass my Husqvarna 430x, but can't manage to pass the credentials window.
-- adding my email and password 
and then in the last field myappkey/clientID (with "/") in the midl but its not working

**Comment by TheCloudScout** [comment]
I'm having the same issue. Adding integration only asks for e-mail, password and key/client Id and not the secret from the Husqvarna dev page. I tried combinations where I entered the secret as a password or entering the secret as a key but I cannot get it to work.

**Comment by TheCloudScout** [comment]
Well apparently I didn't read the instructions properly.... :-(

I missed step 5 of the readme where I needed to app the individual API's to the new "application" in the Husqvarna cloud dashboard. 

https://github.com/py-smart-gardena/hass-gardena-smart-system/blob/master/info.md

Afterwards the integration was added without issues. You don't need the secret, only the key, e-mail address and your password.

**Comment by grm** [comment]
Indeed, you need to declare the aplication in your own husqvarna account and then follow step by step what is described in the README : https://github.com/py-smart-gardena/hass-gardena-smart-system#configuration

I am closing the issue. If you need any additional help, do not hesitate to reopen the ticket ;)

**Comment by lowrisk75** [comment]
I feel very stupid but I still have the same issue.
I even deleted my app and started over.
I even connected all the API (GARDENA smart system API + Authentication API + Automower Connect API)

in home assistant, in the integration popup I keep having Username/Password/API-Key is wrong.

36 Digit API Key is the Application Key
username is my email address
and password is the account password and not the application secret... but yet same issue
