### ISSUE TITLE
Update API Key

### ISSUE THREAD

**Issue by LucTs** [py-smart-gardena/hass-gardena-smart-system#55]
Hi,

integration is working fine so far but I need to update the API key. How can I do that without deleting the integration and installing it again?

Regards

**Comment by grm** [comment]
Hum, that is a good question.
Why do you need to update an API key ?
I am not sure it is currently doable without hand editing some home assistant files and the home assistant database.

**Comment by grm** [comment]
As i have no answer, I suppose it is working now. Do not hesitate to answer this ticket if it is not the case !

Jérémie
