### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'gardena_smart_system'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'gardena_smart_system'

### ISSUE THREAD

**Issue by hillbicks** [py-smart-gardena/hass-gardena-smart-system#57]
> Custom integrations now require a version key in their manifest file, this also means that all custom integrations now require a manifest file.
> 
> If you are using a legacy custom integration like custom_components/awesome.py this now needs to move to custom_components/awesome/__init__.py so you can add custom_components/awesome/manifest.json to it.
> 
> For more information about integration, manifests have a look here: https://developers.home-assistant.io/docs/creating_integration_manifest
> 
> For now, this will create a warning on startup. But this will eventually be blocked from loading if it’s missing a version in the manifest.
> 
> If you see these warnings, please report the issue with the author of that custom integration.

https://github.com/home-assistant/core/pull/45919

**Comment by StephanU** [comment]
See https://github.com/py-smart-gardena/hass-gardena-smart-system/pull/56
