### ISSUE TITLE
Websocket error. 

### ISSUE THREAD

**Issue by strutings** [py-smart-gardena/hass-gardena-smart-system#59]
ERROR (Thread-4) [websocket] error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0x6fffb100>>: on_message() takes 2 positional arguments but 3 were given

All sensors updates on startup, after that i receive this error.

**Comment by MarcusKapun** [comment]
I have the same error:

At start / restart of HA (whereby all sensors update):
ERROR (Thread-6) [websocket] error from callback <bound method Client.on_open of <gardena.smart_system.Client object at 0x6be53bf8>>: on_open() takes 1 positional argument but 2 were given

During normal ops (no update of sensors):
ERROR (Thread-6) [websocket] error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0x6be53bf8>>: on_message() takes 2 positional arguments but 3 were given

Switches (water control in my case) are also not working any more

**Comment by clews** [comment]
Same problem here...

**Comment by grm** [comment]
Hello Clews,

Thx for the insight into the bug. Could you create a PR so we can merege the fix please ?

Thanks a lot !

**Comment by gvdhoven** [comment]
@grm i created the PR for you (it was just 2 clicks) 👍

**Comment by clews** [comment]
Sorry for the late answer, was quite busy in the last weeks. I've added the ws parameter to on_close also. Pushed it to my fork on master, so it'll be taken into account by the actual PR.
With those fixes, the integration work perfectly stable for me on HA (I only use irrigation control).

**Comment by jorgenbosman** [comment]
Any idea when this will be in a new stable release together with version info in the manifest.json? Since the latest hass release, the integration is no longer loaded

**Comment by grm** [comment]
A new version has been released a few minutes ago.
I had no time to test the PR but  I wll try to test it this week end (hopefully).

Jérémie

**Comment by MarcusKapun** [comment]
Unfortunately I have still the same issue with version 0.2.3

Logger: websocket
Source: /srv/homeassistant/lib/python3.8/site-packages/websocket/_logging.py:66
First occurred: 21:13:13 (22 occurrences)
Last logged: 21:13:14

error from callback <bound method Client.on_open of <gardena.smart_system.Client object at 0x69550d90>>: on_open() takes 1 positional argument but 2 were given
error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0x69550d90>>: on_message() takes 2 positional arguments but 3 were given

**Comment by depthchargex** [comment]
Have the same issue also.  Almost everything seems to work except the switches, for example, they don't keep the correct state in sync with the API.  It will turn the water on for example but in HA it shows as turned off.

2021-07-07 15:17:21 ERROR (Thread-4) [websocket] error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0xffff94ae92b0>>: on_message() takes 2 positional arguments but 3 were given

**Comment by FransHalsjes** [comment]
same error after upgrading to 2021.7.0  

Logger: websocket
Source: /usr/local/lib/python3.9/site-packages/websocket/_logging.py:67
First occurred: 10:54:56 (9 occurrences)
Last logged: 10:54:57

error from callback <bound method Client.on_open of <gardena.smart_system.Client object at 0x7f823a05adf0>>: on_open() takes 1 positional argument but 2 were given
error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0x7f823a05adf0>>: on_message() takes 2 positional arguments but 3 were given

**Comment by grm** [comment]
Hello,

A fix has been released in the version 0.8.0 !

Jeremie

**Comment by FransHalsjes** [comment]
I don’t see that version on hacs.. ?

Verstuurd vanaf mijn iPhone

**Comment by tamascp** [comment]
I have the same problem:

Logger: websocket
Source: /usr/local/lib/python3.9/site-packages/websocket/_logging.py:67
First occurred: 2021. július 25. 21:21:14 (91 occurrences)
Last logged: 0:00:44

error from callback <bound method Client.on_open of <gardena.smart_system.Client object at 0x7f90f6f4c0>>: on_open() takes 1 positional argument but 2 were given
error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0x7f90f6f4c0>>: on_message() takes 2 positional arguments but 3 were given

After HA restart the sensors are updated, but only once. If the status of the sensor changes, it will no longer uodate automatically.

**Comment by WW1983** [comment]
> After HA restart the sensors are updated, but only once. If the status of the sensor changes, it will no longer update automatically.

Have the same Problem.

**Comment by eikowagenknecht** [comment]
> I don’t see that version on hacs.. ?

I had the same problem. It seems you need to use Release 0.2.5b3 (or master) of the HASS addon:
![image](https://user-images.githubusercontent.com/1475672/144005959-06f0e8c2-eb9a-4fcd-a282-6c46d229318e.png)

@grm Maybe this can be pushed to the stable branch as well?
