### ISSUE TITLE
Where is homekit code??

### ISSUE THREAD

**Issue by zygote279** [py-smart-gardena/hass-gardena-smart-system#60]
Hi all,

Have followed instructions and have api code etc, however am stuck on getting my homekit code - can't see it anywhere on the gardena hub or my smart watering system. Can't see it in the app either - anyone able to offer any pointers here??

**Comment by Piffis** [comment]
Try the Gardena app under settings -> Homekit. The code should be there.

**Comment by zygote279** [comment]
That's the odd thing, is this the page you mean: 
https://imgur.com/a/O6Dmn6N

No sign of it at all - brand new device...?  App version is 2.4 - has April 2021 update.

Is there anywhere I need to enable this or something?

**Comment by Piffis** [comment]
I run app version 3.1.093 and have another line between Alexa and IFTT.

Can you update your app? Are you on an outdated OS that prevent you from seeing newer app-releases perhaps?
![Uploading 8DB2BA57-B947-49DF-9385-8FBF5DDC6E1D.png…]()

**Comment by zygote279** [comment]
Ah, your response twigged me - the app is OS dependent (was using latest Android on my Pixel and also tried through browser) - installed through iPhone and the homekit option appears!

Only thing now I get is an error saying: The device is already pairing with another controller

Tried restarting the Gardena hub, Home Assistant and also tried reinstalling the HACS component, but error still remains. Definitely was working previously as got homekit prompt - any clues as to how to resolve this error?

**Comment by zygote279** [comment]
Ah, scratch that - apple obviously persist a session or something when using their app. Quitting app completely seemed to fix! All working now!

**Comment by Piffis** [comment]
Great!
And no surprise really that HomeKit (Apple feature) isn’t available on an Android device ;)
I thought you were using an iPhone :)

**Comment by zygote279** [comment]
I know... long day..... ;)
