### ISSUE TITLE
Translation dutch

### ISSUE THREAD

**Issue by Rraets** [py-smart-gardena/hass-gardena-smart-system#63]
When the mower is "mowing"  the result state is in dutch "reinigen" . That means cleaning.
It should be "mowing'

**Comment by grm** [comment]
Hello,

Thx for the feedback, are you talking in Home assistant ?

**Comment by Rraets** [comment]
Sorry it should be "maaien" instead of "reinigen"
Yes its in Home Asistant.

**Comment by jeremycoppey** [comment]
I have the same in english, it says: "cleaning" instead of mowing

**Comment by benjycov** [comment]
Its because the mower is actually seen as vacuum cleaner in HA, HA has no
mower class. Hence cleaning instead of mowing :)

**Comment by grm** [comment]
Indeed, i am planning to create a mower component instead of vacuum and it should work in it !
Jeremie

**Comment by jborup** [comment]
@grm I think this is actually possible to handle just with translations, the characteristics of mower and cleaner are the same except for the wording, so maybe just a translation can handle this?
