### ISSUE TITLE
[question] what elements I need to have to integrate

### ISSUE THREAD

**Issue by gmichale** [py-smart-gardena/hass-gardena-smart-system#64]
hi,

wanted to make sure beucase I am before buying smart gardena system. 
Do I need also smart gardena gateway or having HA only allow me to integrate SMART WATER CONTROL ?

**Comment by Piffis** [comment]
You need gateway

**Comment by gmichale** [comment]
do you know any other systems which integrates with HA directly via WiFi or zigbee?

**Comment by Piffis** [comment]
A bit off topic, but:
You could use a Zigbee/WiFi relay to open the sprinkler valves. But for the zigbee you need a zigbee hub instead.

I use Fibaro dry relays. Power them with 230vac and send 24vac in/out of the relays in order to control my Hunter valves.

**Comment by benjycov** [comment]
You easily knock something up with ESPHome and a relay board, then some off
the peg 24v irrigation valves.

**Comment by grm** [comment]
Hello, 

You could use any system to open valves as stated, relay boards, wifi/zwave devices.
But this library focus on gardena system and using the gardena valve system to control them.

Using other devices can be used, but they must be used using their own protocol, this library supporting only the gardena one :)

**Comment by grm** [comment]
As answered, you need the gateway, wich is the bridge between your garden and gardena/HA !

Jérémie
