### ISSUE TITLE
No 'version' key in manifest

### ISSUE THREAD

**Issue by TOBx2** [py-smart-gardena/hass-gardena-smart-system#66]
Home Assistant's log contains the following error message:

---8<---8<---8<---
 No 'version' key in the manifest file for custom integration 'gardena_smart_system'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'gardena_smart_system'
---8<---8<---8<---

**Comment by SNoof85** [comment]
It has been adressed in #56 but since there hasn't been any new release of the integration (only a pre release wich is not seen in HACS)

**Comment by GLehnhoff** [comment]
Same to me. Configuration not possible, usage not possible:

2021-05-21 17:53:28 ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'gardena_smart_system'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'gardena_smart_system'

**Comment by GLehnhoff** [comment]
Well, I got it.
First, I used the latest Beta version 0.2.3b2 and installed new via HACS.
Then restart HA Core.
Then the plugin is within HA Integrations (to be searched for), NOT within the HACS integration (documentation should be improved).
Then it run in an error.
Then restart HA core again. 
And all entities are there.
:-)

**Comment by alexfiftyfour** [comment]
Worked for me too. Updated to Beta version 0.2.3b2. Computer restart and integration works. My "sheep" is available and waiting to eat my grass. ;-)

**Comment by SNoof85** [comment]
Updated to beta but not with HACS ? Manual setup right ?

**Comment by alexfiftyfour** [comment]
I did everything with HACS. My HACS shows the Beta version 0.2.3b2. So I just clicked, switched, rebooted and DONE :-)

**Comment by GLehnhoff** [comment]
Same with me. However, as written above, I had to reboot twice.

**Comment by grm** [comment]
Should be good now ! A release has been made containing the version info :)
