### ISSUE TITLE
Integration not found

### ISSUE THREAD

**Issue by Johnyyy85** [py-smart-gardena/hass-gardena-smart-system#67]
Hi, 

I updated HA to the newest version yesterday. 2021.6.
After that the Gardena integration doesn't work.

logger: homeassistant.setup
Source: setup.py:172
First occurred: 8:45:20 (1 occurrences)
Last logged: 8:45:20
Setup failed for gardena_smart_system: Integration not found.

**Comment by spitz66** [comment]
This worked for me:
![image](https://user-images.githubusercontent.com/65921206/120610697-bdc3fd80-c453-11eb-917a-d5cc1305bdf1.png)

**Comment by Johnyyy85** [comment]
it worked. thanks

**Comment by grm** [comment]
Hello, I am going to release a new version to avoid these issues in the
future !
