### ISSUE TITLE
new sensor with less sensors

### ISSUE THREAD

**Issue by leonardpitzu** [py-smart-gardena/hass-gardena-smart-system#69]
Gardena has a new smart sensor which has less sensors than the old (now obsolete) one.
the new sensor is: https://www.gardena.com/int/products/smart/smart-system/smart-sensor/967986501/
new model type: 19040-20

in the picture below are the unavailable sensors
![gardena](https://user-images.githubusercontent.com/4321813/120762178-aa319900-c51e-11eb-84ef-6df4fb8a8cc2.png)

**Comment by grm** [comment]
The sensor is now available and working :)
