### ISSUE TITLE
No state fedback from Water Control -> cannot stop watering by switch

### ISSUE THREAD

**Issue by Blackhawk386** [py-smart-gardena/hass-gardena-smart-system#71]
Hi,

I use your plugin to control a Gardena Water Control with Home Assistant. Adding integration worked, a new switch for Water Control was created. With it I can start watering but unfortunately I don't get a state feedback so the switch fals back to "off" in HA even when Water Control is switched on. Following from this problem, it is impossible to send a "switch off" command to stop water control.
Hope someone can help...
Thanks in advance!

**Comment by phantomski77** [comment]
Same issue here. Since `core-2021.7.0` the current state is not reported back to the switch entity - it doesn't change state, it's not reported in history. `switch.turn_on` still works.

**Comment by fabsenet** [comment]
as far as I can tell, its the same for my mower. the commands work, but the state is fetched once on HA startup and never gets updated. I already reinstalled the integration completely with a complete new api app key and everything from gardena. no change.

**Comment by fabsenet** [comment]
oh I should have read the other issues first. https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/81 helped me. 0.2.5b3 seems to do the trick for me. @Blackhawk386  you may want to check that yourself as well.

**Comment by phantomski77** [comment]
Can confirm 0.2.5b3 fixes the issue with broken feedback and also there are no error messages. All working now. Thanks @grm !

**Comment by grm** [comment]
Good to know !

I close the issue, feel free to reopen it if needed !

**Comment by Blackhawk386** [comment]
Same for me, works perfect with 0.2.5b3. Thanks a lot!
