### ISSUE TITLE
vacuum.return_to_base dont work as expected 

### ISSUE THREAD

**Issue by strutings** [py-smart-gardena/hass-gardena-smart-system#73]
With the command vacuum.return_to_base the mower cancels the current operation and returns to charging station, but It will not 
 reactivate with the todays schedule but jumps directly to next day schedule.  

Im trying to implement a rain sensor with gardena to stop the mower based on rainrate from my Davis weather station. 

Is this a known bug or expected behavior?

**Comment by grm** [comment]
The option to control mower using the api are very limited.

I have two option : 
- return to base and ignore schedule
- return to base and resume schedule, but i have no control and when is the next schedule.

To achieve what you are trying to do, you will have to schedule directly in home assistant and not use the gardena scheduler and control every aspect of the mower automation.
For now, there is no plan to add a scheduler into this integration, but maybe some day !


Sorry about that,
Jérémie
