### ISSUE TITLE
[Question/FR]Force update of sensor value possible

### ISSUE THREAD

**Issue by hillbicks** [py-smart-gardena/hass-gardena-smart-system#75]
Hi,

the update interval of the gardena sensor is really inconsistent, sometimes there are more than 6 hours without an update to the soil humidity sensor. I want to start the watering process at a specific time during the night, it would be great to have current sensor data available. 

I know from using the gardena app that I can force an update manually. Would it be possible to have this feature for the sensor?

Thanks!

**Comment by grm** [comment]
Hello,

The functionality you are talking about is not available in the official API, but only the un-official one.

I don't want to have this kind of unofficial endpoint in the integration, gardena may change it without us knowing or it can be stopped anytime !

It is a totally different api nit public.

Sorry about that !
Jérémie
