### ISSUE TITLE
hardware switch to ignore schedule

### ISSUE THREAD

**Issue by zobi** [py-smart-gardena/hass-gardena-smart-system#80]
Hello, i would like to make an hardware switch for : 
 - when on : switch off my mower and ignore schedule
 - when off : start in next schedule.
i would like to use gardena application sometimes 
i tried to make autmation with trigger on vaccum.mower but sometimes it work's sometimes not ... 
can u help me plz ?

**Comment by grm** [comment]
Hum, when it does not work, could you have a look to the logs and 0aste them here so i can check ?
Did you use the service **park_until_further_notice** to stop the schedule and **park_until_next_task** to restart the schedule ?

Jeremie

**Comment by zobi** [comment]
Hello and thank you for your response.
I'm not an expert and i don't where to find the good log ?
No i didn't use this service because i don't know where to find this too
... i use trigger with state status at : PARKED_TIMER or
PARKED_PARK_SELECTED. How to use *park_until_next_task* ? Thanks a lot for
your help

Le jeu. 8 juil. 2021 à 19:26, Jérémie Klein ***@***.***> a
écrit :

**Comment by grm** [comment]
Hey,

as we are currently using a vacuum integration, we need to map our statuses to the available ones.
Here is the vacuum sevice mapping : 

```
    def start(self):
        """Start the mower using Gardena API command START_SECONDS_TO_OVERRIDE. Duration is read from integration options."""
        self._device.start_seconds_to_override(duration)

    def stop(self, **kwargs):
        self._device.park_until_further_notice()

    def turn_on(self, **kwargs):
        self._device.start_dont_override()

    def turn_off(self, **kwargs):
        self._device.park_until_further_notice()

    def return_to_base(self, **kwargs):
        self._device.park_until_next_task()
```

so you will have to call the service : 
- *vacuum.turn_off* with your entity_id to stop completely the mower
- *vacuum.stop* to make the schedule available again


I know that using the stop command seems counter-intuitive, but it is becaue we have to stick ith the vacuum interface whih is not adaptd for everything to a vacuum :) 

Please let me know if it works for you !

Jérémie

**Comment by zobi** [comment]
Hello yes i use this services vacuum.turn_off and stop. But i confirm i didn't work every time !
I have enable log debug and i see an error .
To reproduce use gardena on ios to switch scheduler on and on log i have :  

`2021-07-14 19:54:43 ERROR (Thread-3) [websocket] error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0x7fc0fbc08c10>>: on_message() takes 2 positional arguments but 3 were given`

Thanks again

**Comment by zobi** [comment]
I see this issue : https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/59
i think i have exactly the same problem ... I use last update of your plugin : 0.2.3 and last update of HA : core-2021.7.3 & supervisor-2021.06.8
you talk about 0.8.x version what is it ? 
Thanks a lot

**Comment by zobi** [comment]
Hello @grm are you already in holidays?
Thanks a lot

**Comment by grm** [comment]
Hello,

there has been a lot of changes reecently in the library.
Could you give it another shot please and recreate a ticket if you still have an issue ?

Thx
