### ISSUE TITLE
gardena sensor is never updated

### ISSUE THREAD

**Issue by sebkrick** [py-smart-gardena/hass-gardena-smart-system#83]
Hello
Values of the gardena sensor are never updated. Values in lovelace remain at values from start up. This happens with the automatically generated lovelace dashboard, but also with a custom one.
I am using v0.2.3 with hacs and core-2021.7.4.
Any idea?

**Comment by footy84** [comment]
Hi,

have the same issue here. Mower attributes(battery,status)  are not updating.
The status request only works once if I reboot(configuration>server controls) the homeassistant server. 
Environment:
- docker 20.10.7
- homeassistant 20210707.0 - latest
- HACS 1.13.2
- Gardena Smart 0.2.3 > installed via the integration

thank you

**Comment by thecem** [comment]
Go to HACS reinstall Gardena with beta option and you are done:

@
![B2F6F4D1-41C3-4AF3-8E7A-A153182BB8BD](https://user-images.githubusercontent.com/46648579/127992100-7337e289-ef9d-4f56-bd5c-9c550b7db12f.jpeg)

**Comment by sebkrick** [comment]
Many thanks, that helped indeed!

**Comment by aahlborg** [comment]
I had the opposite problem as I Installed the integration manually from master but had an older Home assistant.

Btw, the README states "Requires Home Assistant 0.110 or newer". This should be updated.
